networks:
  net:

services:
  backend:
    build: ./backend/hack/
    command: gunicorn hack.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/hack:/app
      - static_volume:/backend/hack/static
      - media_volume:/backend/hack/media
    restart: unless-stopped
    networks:
      - net
  frontend:
    build:
      context: ./frontend/front/
      dockerfile: Dockerfile
    networks:
      - net
    restart: unless-stopped
    
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend 
    networks:
      - net
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  
