services:
  backend:
    build: ./backend/hack
    volumes:
      - ./backend/hack:/app
    command: gunicorn --pythonpath /app hack.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=hack.settings
    restart: unless-stopped

  frontend:
    build: ./frontend/front
    environment:
      BACKEND_HOST: backend
    volumes:
      - ./frontend/front/dist:/usr/share/nginx/html
      - ./frontend/front/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
    expose:
      - "80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/front/dist:/usr/share/nginx/html
      - ./backend/hack/static:/usr/share/nginx/html/static
      - ./backend/hack/media:/usr/share/nginx/html/media
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
  
