# Generated by Django 5.2 on 2025-04-04 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_reaction', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.3)])),
                ('acceleration', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('max_speed', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(3.0), django.core.validators.MaxValueValidator(15.0)])),
                ('coef', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(0.0)])),
            ],
        ),
    ]
