# Generated by Django 5.2 on 2025-04-05 00:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterField(
            model_name='person',
            name='acceleration',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.1)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='coef',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='max_speed',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(15.1)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='time_of_reaction',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.31)]),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='runs.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': ('Результат',),
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
