# Generated by Django 5.2 on 2025-04-04 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='max_speed',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(15.0)]),
        ),
    ]
