# Generated by Django 5.2 on 2025-04-04 23:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_alter_person_max_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='acceleration',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.1)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='coef',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='max_speed',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(15.1)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='time_of_reaction',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.31)]),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='runs.person')),
            ],
        ),
    ]
