# Generated by Django 5.2 on 2025-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0007_alter_result_options_alter_result_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='color',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
