# Generated by Django 5.2 on 2025-04-06 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0010_alter_person_options_alter_result_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id'], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='person',
            name='acceleration',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.1)], verbose_name='Ускорение'),
        ),
        migrations.AlterField(
            model_name='person',
            name='coef',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(-2.1), django.core.validators.MaxValueValidator(0.1)], verbose_name='Коэффициент'),
        ),
        migrations.AlterField(
            model_name='person',
            name='color',
            field=models.CharField(help_text='HEX-код цвета (#FFFFFF)', max_length=16, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='person',
            name='max_speed',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(15.1)], verbose_name='Макс. скорость'),
        ),
        migrations.AlterField(
            model_name='person',
            name='time_of_reaction',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.31)], verbose_name='Время реакции'),
        ),
    ]
